Implement standard create assertion
target/consensource-cli pull request #11
Opened 2020-08-04 18:04 UTC by pa3ng

## Proposed change/fix

Implement CLI assertions for standards creation.

## Types of changes

What types of changes does this pull request introduce to ConsenSource? _Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (could be a small readme update, documentation contribution, etc.)

## How to run/test

**WIP**

2020-08-04 20:33 UTC, adeebahmed requested changes
![image](https://user-images.githubusercontent.com/11996230/89341978-bc754900-d667-11ea-8e2e-f2b3eed919f2.png)

This usage dialog doesn't look right

2020-08-05 15:41 UTC, pa3ng commented
![image](https://user-images.githubusercontent.com/11638786/89433588-22191200-d708-11ea-8ab6-b06ecb158f04.png)
Usage dialog for `csrc assertion standard create` should look like this ^

2020-08-10 16:09 UTC, Patrick-Erichsen commented
LGTM 👍

2020-08-10 16:18 UTC, adeebahmed approved these changes

2020-08-10 16:22 UTC, merged